version: '3.8'

services:
  # ====================================================================
  # I. DỊCH VỤ DATABASE (POSTGRESQL)
  # ====================================================================

  db_auth:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: PGB_AuthDb
    volumes:
      - auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d PGB_AuthDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_todo:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: PGB_TodoDb
    volumes:
      - todo_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d PGB_TodoDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_chat:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: PGB_ChatDb
    volumes:
      - chat_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d PGB_ChatDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ====================================================================
  # II. DỊCH VỤ AUTH API
  # ====================================================================

  pgb.auth.api:
    build:
      context: . 
      dockerfile: PGB.Auth.Api/Dockerfile
    ports:
      - "7001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db_auth;Port=5432;Username=user;Password=password;Database=PGB_AuthDb
      JwtSettings__SecretKey: change_this_to_a_strong_secret_for_dev 
    depends_on:
      db_auth:
        condition: service_healthy

  # ====================================================================
  # III. DỊCH VỤ TODO API
  # ====================================================================

  pgb.todo.api:
    build:
      context: .
      dockerfile: PGB.Todo.Api/Dockerfile
    ports:
      - "7002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db_todo;Port=5432;Username=user;Password=password;Database=PGB_TodoDb
    depends_on:
      db_todo:
        condition: service_healthy

  # ====================================================================
  # IV. DỊCH VỤ CHAT API
  # ====================================================================

  pgb.chat.api:
    build:
      context: .
      dockerfile: PGB.Chat.Api/Dockerfile
    ports:
      - "7003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db_chat;Port=5432;Username=user;Password=password;Database=PGB_ChatDb
      OpenAI__ApiKey: sk-your-ai-key-here
    depends_on:
      db_chat:
        condition: service_healthy

  # ====================================================================
  # V. API GATEWAY
  # ====================================================================

  pgb.apigateway:
    build:
      context: .
      dockerfile: PGB.ApiGateway/Dockerfile
    ports:
      - "7000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      JwtSettings__SecretKey: change_this_to_a_strong_secret_for_dev 
      JwtSettings__Issuer: PGB_ORG
      JwtSettings__Audience: PGB_ORG_Users
    depends_on:
      - pgb.auth.api
      - pgb.todo.api
      - pgb.chat.api

# ====================================================================
# VI. VOLUMES
# ====================================================================
volumes:
  auth_data:
  todo_data:
  chat_data: