# render.yaml - Phiên bản đã sửa lỗi cú pháp hoàn chỉnh

# ==========================================
# I. ĐỊNH NGHĨA CÁC DATABASE
# Databases phải được định nghĩa ở mục riêng này
# ==========================================
databases:
  - name: pgb-auth-db
    databaseName: pgb_auth_db # Tên database sẽ được tạo
    user: pgb_user # Tên user
    plan: free # Chọn gói miễn phí

  - name: pgb-todo-db
    databaseName: pgb_todo_db
    user: pgb_user
    plan: free

  - name: pgb-chat-db
    databaseName: pgb_chat_db
    user: pgb_user
    plan: free

# ==========================================
# II. ĐỊNH NGHĨA CÁC SERVICES
# ==========================================
services:
  # --- Backend Microservices (chạy nội bộ, không public) ---
  - name: pgb-auth-api
    type: web # Vẫn là 'web' nhưng sẽ không public nếu không có 'routes'
    runtime: docker
    dockerfilePath: ./PGB.Auth.Api/Dockerfile
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: pgb-auth-db
          property: connectionString # Lấy chuỗi kết nối từ database đã